
# 工具相关配置
gfcli:
  # 工具编译配置
  build:
    name:     "focus"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      - link:            "mysql:root:my-secret-pw@tcp(192.168.0.69:3306)/focus?charset=utf8mb4&parseTime=true&loc=Local"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        tables: "p_cate"
